# Generated by Django 3.2 on 2021-04-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='choicefield',
            field=models.CharField(max_length=20),
        ),
    ]
